sudo: false

language: node_js
node_js:
  - "node"

before_install:
  - pip install --user mkdocs

script:
  - PATH=$PATH:$HOME/.local/bin mkdocs build -d public

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  project: bridgefoundry-operations
