name: Build and deploy website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
    - name: Deploy
      run: mkdocs gh-deploy --verbose --force
